from pydantic import BaseModel, Field, HttpUrl
from typing import List, Optional
from uuid import UUID

# --- Schemas for Camera Data sent from Edge PC ---

class RTSPStreamSchema(BaseModel):
    """Data model for a single RTSP stream discovered locally on the Edge PC."""
    # The RTSP URL must be sent as a string by the edge device.
    # Using HttpUrl from Pydantic provides basic URL validation.
    rtsp_url: HttpUrl = Field(..., description="The full RTSP URL of the camera stream.")

    # A temporary name provided by the local config file, if available.
    local_name: Optional[str] = Field(None, max_length=100)

    # We enforce that no extra fields are sent by the Edge PC, which is safer.
    model_config = {
        "extra": "forbid"
    }

class DeviceHandshakeSchema(BaseModel):
    """The full payload sent from the Edge Docker on initial connection."""

    # The secret token generated by the central system and stored in the 'devices' table.
    device_token_secret: str = Field(..., min_length=32)

    # The list of cameras discovered on the local network.
    cameras: List[RTSPStreamSchema]

    # Information about the Edge PC itself (e.g., hostname, version)
    hostname: str = Field(..., max_length=100)

    # We enforce that no extra fields are sent by the Edge PC, which is safer.
    model_config = {
        "extra": "forbid"
    }

class DeviceProvisionSchema(BaseModel):
    """Input model for provisioning a new device and organization (Admin use)."""
    organization_name: str = Field(..., max_length=255)
    device_name: str = Field(..., max_length=255)

class ProvisionResponseSchema(BaseModel):
    """Output model for the provisioning response."""
    organization_id: UUID
    device_id: UUID
    # This is the secret key used for the Edge Docker deployment (VERY sensitive!)
    device_token_secret: str
    message: str = "Device and organization provisioned successfully."

class DeviceResponse(BaseModel):
    """Output model for listing Edge Devices/Cameras."""
    id: UUID
    organization_id: UUID
    name: str
    status: str

    # Critical: Include rule fields for the frontend to know current config
    require_helmet: Optional[bool] = False
    require_vest: Optional[bool] = False
    require_gloves: Optional[bool] = False

    # Schema for the rule update payload (Simplified, no drawing zone)
    class CameraRuleUpdate(BaseModel):
        device_id: UUID
        name: str
        require_helmet: bool = False
        require_vest: bool = False
        require_gloves: bool = False

    model_config = {
        "from_attributes": True
    }

class CameraRuleUpdate(BaseModel):
    """Input model for updating rules for a specific camera (simplified)."""
    device_id: UUID  # The ID of the camera/Edge Device being configured

    # New: Allow changing the human-readable name
    name: str = Field(..., max_length=255)

    # Required PPE (used by the ML model)
    require_helmet: bool = False
    require_vest: bool = False
    require_gloves: bool = False

    # NOTE: DetectionZone and detection_zone list are REMOVED.

class CameraRuleResponse(BaseModel):
    """Output model for the successful camera rule update."""
    device_id: UUID
    message: str = "Camera rules updated successfully."