from sqlalchemy import Column, String, ForeignKey, Boolean
from sqlalchemy.orm import relationship
from sqlalchemy.dialects.postgresql import UUID
from .base import BaseModel


class User(BaseModel):
    """Corresponds to the 'users' table."""
    __tablename__ = 'users'

    # Foreign Key linking back to Organization (Multi-Tenancy Key)
    organization_id = Column(
        UUID(as_uuid=True),
        ForeignKey('organizations.id', ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    email = Column(String(255), nullable=False, unique=True)
    # Stores the bcrypt hash generated by security.py
    password_hash = Column(String(255), nullable=False)
    # Role defines access level (e.g., GlobalAdmin, Supervisor, ViewOnly)
    role = Column(String(50), nullable=False, default="Supervisor")
    is_active = Column(Boolean, default=True, nullable=False)

    # Define relationship
    organization = relationship("Organization", backref="users")