from sqlalchemy import Column, String, ForeignKey, Boolean, DateTime
from sqlalchemy.orm import relationship
from sqlalchemy.dialects.postgresql import UUID
from .base import BaseModel


class User(BaseModel):
    """Corresponds to the 'users' table."""
    __tablename__ = 'users'

    # Foreign Key linking back to Organization (Multi-Tenancy Key)
    organization_id = Column(
        UUID(as_uuid=True),
        ForeignKey('organizations.id', ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    username = Column(String(100), unique=True, nullable=False, index=True)
    email = Column(String(255), nullable=False, unique=True)
    password_hash = Column(String(255), nullable=False) # Stores the bcrypt hash generated by security.py
    role = Column(String(50), nullable=False, default="Supervisor")# Role defines access level (e.g., GlobalAdmin, Supervisor, ViewOnly)
    is_active = Column(Boolean, default=True, nullable=False)
    phone_number = Column(String, nullable=True)
    is_2fa_enabled = Column(Boolean, default=False, nullable=False)
    otp_hash = Column(String, nullable=True)  # We store the hash, not the plain code for security
    otp_expires_at = Column(DateTime, nullable=True)
    # Define relationship
    organization = relationship("Organization", backref="users")